#!/bin/bash

sudo -u enterprisedb /vagrant/upgrades/'01_[enterprisedb]_show_version.sh'
sudo -u enterprisedb /vagrant/upgrades/'02_[enterprisedb]_switchover.sh'
sudo -u root /vagrant/upgrades/'03_[root]_stop_postgres.sh'
sudo -u root /vagrant/upgrades/'04_[root]_install_edb_pgd5.sh'
sudo -u root /vagrant/upgrades/'05_[root]_create_new_data_directories.sh'
sudo -u enterprisedb /vagrant/upgrades/'06_[enterprisedb]_initdb_epas16.sh'
sudo -u enterprisedb /vagrant/upgrades/'07_[enterprisedb]_copy_config.sh'
sudo -u root /vagrant/upgrades/'08_[root]rename_pgdata.sh'
sudo -u enterprisedb /vagrant/upgrades/'09_[enterprisedb]_stop_instances.sh'
sudo -u enterprisedb /vagrant/upgrades/'10_[enterprisedb]_bdr_pg_upgrade_check.sh'
sudo -u enterprisedb /vagrant/upgrades/'11_[enterprisedb]_bdr_pg_upgrade.sh'
sudo -u root /vagrant/upgrades/'12_[root]_amend_service.sh'
sudo -u root /vagrant/upgrades/'13_[root]_start_postgres.sh'
sudo -u enterprisedb /vagrant/upgrades/'14_[enterprisedb]_check.sh'
sudo -u enterprisedb /vagrant/upgrades/'15_[enterprisedb]_upgrade_extensions.sh'
sudo -u enterprisedb /vagrant/upgrades/'16_[enterprisedb]_vacuumdb.sh'
sudo -u enterprisedb /vagrant/upgrades/'17_[enterprisedb]_reenable_access.sh'
sudo -u enterprisedb /vagrant/upgrades/'18_[enterprisedb]_switchover.sh'
sudo -u root /vagrant/upgrades/'20_[root]_remove_old_epas.sh'
